----------------------------------------------------------------------------------------------------
-- 연습 테이블 삭제
----------------------------------------------------------------------------------------------------

-- 고객 관련 테이블

DROP TABLE TB_CUSTOMER CASCADE CONSTRAINTS;
DROP TABLE TB_ADD_CUSTOMER CASCADE CONSTRAINTS;
DROP TABLE TB_POINT CASCADE CONSTRAINTS;
DROP TABLE TB_POINT_2017 CASCADE CONSTRAINTS;
DROP TABLE TB_POINT_2018 CASCADE CONSTRAINTS;
DROP TABLE TB_POINT_2019 CASCADE CONSTRAINTS;
DROP TABLE TB_ETC_INFO CASCADE CONSTRAINTS;
DROP TABLE TB_ITEM_INFO CASCADE CONSTRAINTS;

-- 성적 관련 테이블

DROP TABLE TB_GRADE CASCADE CONSTRAINTS;
DROP TABLE TB_GRADE_07 CASCADE CONSTRAINTS;
DROP TABLE TB_GRADE_08 CASCADE CONSTRAINTS;
DROP TABLE TB_GRADE_09 CASCADE CONSTRAINTS;
DROP TABLE TB_GRADE_2020 CASCADE CONSTRAINTS;
DROP TABLE TB_CLASS_INFO CASCADE CONSTRAINTS;

-- 판매 관련 테이블

DROP TABLE TB_SALES CASCADE CONSTRAINTS;
DROP TABLE TB_SALES_09 CASCADE CONSTRAINTS;

-- 열차 관련 테이블

DROP TABLE TB_TRAIN_TM CASCADE CONSTRAINTS;

-- 사용자 기능 연습 관련 테이블

DROP TABLE TB_POINT_INFO CASCADE CONSTRAINTS;
